### ISSUE TITLE
Gambit installs header files in $prefix/include/libgambit which depend on non-installed config.h

### ISSUE THREAD

**Issue by mkoeppe** [gambitproject/gambit#207]
libgambit appears to be an installed, headers-only C++ library.
However, `libgambit/gambit.h` uses `#include <config.h>`, referencing a configuration header that is not installed (and should not). See http://stackoverflow.com/questions/19586211/correct-installation-of-config-h-for-shared-library-using-autotools

**Comment by jdemeyer** [comment]
This should be considered a very serious issue. It prevents installation of the Python interface with `pip`.

**Comment by mkoeppe** [comment]
resolution is ...?

**Comment by kcrisman** [comment]
See https://github.com/gambitproject/gambit/commit/dcfee30dc80d1d8a291f718634062889e72772fe which apparently is what resolves this.

**Comment by mkoeppe** [comment]
... which is a non-solution because now client code of the headers of the library has the burden of providing the correct definitions, such as of `HAVE_DRAND48` in https://github.com/gambitproject/gambit/blob/e311dbedbd83f6d15f8c6dacc8063afad459950d/library/include/gambit/agg/agg.h#L307

**Comment by kcrisman** [comment]
> ... which is a non-solution because now client code of the headers of the
> library has the burden of providing the correct definitions, such as of
> HAVE_DRAND48 in
> https://github.com/gambitproject/gambit/blob/e311dbedbd83f6d15f8c6dacc8063afad459950d/library/include/gambit/agg/agg.h#L307
>
> Got it - just looked at this because a user was asking about using Gambit
and I wanted to check on the status.

>

**Comment by tturocy** [comment]
@mkoeppe It is perhaps unhelpful to make such sweeping claims without an understanding of the codebase.  Relevant points:

(1) It is not intended (anymore, going forward) that Gambit is buildable as a shared library.  Relying on config.h is problematic, especially for building Python - which are the complaints which dcfee30 addresses.
(2) Build systems are fully capable of automating the setting of flags if needed.  Indeed the build system does so correctly when building the C++ tools.  And indeed prior to the ill-considered use of config.h, it had done so quite happily for two decades.
(3) The only thing that config.h was providing is HAVE_SRAND48 and HAVE_DRAND48.  Fallbacks exist for these in all places in the code, and indeed the correct functioning of the code does not depend on srand48() and drand48() existing.  They are used only for starting points or perturbation vectors, and the intention in future is that these should be provided by the caller so the caller can correctly control the reproducibility of their calculations, rather than black-boxing the randomisation.

**Comment by mkoeppe** [comment]
Thanks for opening a line of communication. It will be positive for the Sage project if at some point in the future this project becomes usable again. It sounds like you have a plan; good luck with it.

**Comment by kcrisman** [comment]
@tturocy perhaps more directly, is there a possible timeline for a new release of Gambit?  at least [the docs](https://gambitproject.readthedocs.io/en/latest/) of the 16.0.1 still use Python 2 syntax and references 2014 - but I know that https://github.com/gambitproject/gambit/commit/b0f989d32dfb081ab3b91339230bb7b72e0d51f6 says it is Python 3 ready.  A Py3 compatible (maybe even pip-installable?) released version would be great; I do semi-regularly get correspondence asking about Gambit because I helped slightly with packaging it for Sage in the long ago past, as does our help list, and we'd love to support it again (though our packaging system has changed somewhat since that time).

**Comment by tturocy** [comment]
I have been a dean for five years, which has left me very little time to do my own research - much less software packaging.  I am a big fan of Sage.  However, from my point of view, telling me that the Gambit build architecture is dated is not that helpful.  I know it is desperate need of modernisation and improvement.  I get lots of people telling me this.  I do not get a lot of people saying they would like to help me do something about it.  If it is down to me finding the time to deal with things, then the wait time could be arbitrarily long.

I would very much love nothing more than to be able to spend a lot of time on Gambit.  At present my day job does not permit this.

**Comment by kcrisman** [comment]
>
> I would very much love nothing more than to be able to spend a lot of time
> on Gambit. At present my day job does not permit this.
>

I, for one, can identify with this.  That also gives a helpful (if
unfortunate) timeline - thank you!
