### ISSUE TITLE
Importing pay-off matrix?

### ISSUE THREAD

**Issue by sklipnoty** [gambitproject/gambit#225]
Hello all 

I have a pay-off matrix in excel roughly 16*22. However I cannot seems to find an easy way to turn this into a .nfg format? Could someone plz elaborate on how to turn pay-off matrices into a valid format?
 
Also is it possible to add negative numbers? 

My regards

**Comment by sklipnoty** [comment]
So from what I've found adding a larger pay-off matrix is simply copy-pasting it in. What a very cryptic description in the documentation without examples of bigger matrices. 

Negative values seem a no go and also no float or double. 

What is the max allowed dimension for this program?

**Comment by tturocy** [comment]
There's no mention of copy-paste in the documentation, because it would usually be expected that a graphical interface would receive a copy-paste operation.

Negative numbers are fully supported and will be no problem.  Decimal numbers likewise.  Note that all numbers are interpreted as exact, as explained in the documentation.

There is no maximum size, although if you are wanting to compute equilibria, remember that running time of equilibrium finding is exponential in the size of the game.

**Comment by sklipnoty** [comment]
Ok after playing around a little bit more, I should've updated this topic. (I forgot to do so, my apologies). 

My feedback in importing the data:

First of all I have a spreadsheet which contains the pay-off matrices. The reproduce this data in Gambit, I made a .nfg file. The header information is well documented and I never had any errors there. However for some reason the input-system of gambit wants to know the pay-off for both strat 1 for both players and later wants the pay-off for the next strategy which means you cannot directly copy a table (as is) from a spreadsheet to a .nfg-file. I solved this by adding enter after each pay-off column. I personally found this counter-intuitive and this could use a less cryptic description in the doc. Enless there is some other way I can easily turn my matrices into a format readable by Gambit?

Float values are a go, but for some reason in the interface are shown as fractions. Is there an option to turn this off? I used , instead of . , as a result of directly copy-pasting, perhaps a better error description would also help.  (instead of format not recognized by ... ) 

My regards

**Comment by tturocy** [comment]
Could you recommend some text for a "less cryptic description"?

You cannot use "floating point" numbers; payoffs must be exactly represented (otherwise you run into problems with, among other things, the well-definedness of equilibrium, because of rounding errors).  So in this case Gambit is doing the "right thing."

**Comment by sklipnoty** [comment]
(keep this)
The assignment of the numeric data in this list to the entries in the strategic game table proceeds as follows. The list begins with the strategy profile in which each player plays their first strategy. The payoffs to all players in this contingency are listed in the same order as the players are given in the prologus. 
(add)
When you are working with the 'standard' representation of a pay-off matrix, this means that you have to enter pay-off column per pay-off column. A pay-off column contains the pay-off values for all the players for those strategies. In the example file this the first pay-off column would be 11 02 02.  (Warning: you cannot simply use the 'standard' representation of a pay-off matrix, this will result in another pay-off matrix being generated)
(perhaps - difference between)
1 1 1 1
0 2 0 3  
0 2 2 0
!=
11 02 02 11 03 20

Something like that, feel free to change it around.
