### ISSUE TITLE
Is Gambit GUI capable enough to solve a six player simultaneous game.

### ISSUE THREAD

**Issue by Sud26** [gambitproject/gambit#241]
I have a six player simultaneous game with 729 possible combinations. Is Gambit GUI efficient enough to solve for pure as well as mixed strategies of a payoff matrix this big ?

Thanking you in advance.

**Comment by stengel** [comment]
Dear Sudhan:

this may exceed the current capabilities of Gambit (but
perhaps not). We are working on improved algorithms for such
problems. Would you be willing to share your game as a test
case for this with us, with your contact data?

Many thanks,
-Bernhard von Stengel 

* Sudhan Patil <notifications@github.com> [23-07-2018 18:28:36 -0700]:

> I have a six player simultaneous game with 729 possible combinations. Is Gambit GUI efficient enough to solve for pure as well as mixed strategies of a payoff matrix this big ?
> 
> Thanking you in advance.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gambitproject/gambit/issues/241

-- 
Prof Bernhard von Stengel         email: stengel@nash.lse.ac.uk
Department of Mathematics         http://www.maths.lse.ac.uk/Personal/stengel
London School of Economics        phone: +44-20-7955 6438  (office)
Houghton St, Room COL 4.12               +44-20-7226 2325  (home)
London WC2A 2AE, United Kingdom

**Comment by tturocy** [comment]
For pure strategies this will be no problem. For all mixed strategies, this is computationally a difficult problem - as such, it is not per se a question of whether Gambit is efficient, because no (known) algorithm can be "efficient" to find all mixed strategies in such a game.  It will depend on the game.  As @stengel noted, there is active work around developing better methods for computing all mixed strategy equilibria of 3+ player games, but a "better" method might still take an extremely long time (days? weeks?) even if implemented efficiently, for some games.
