### ISSUE TITLE
BUG: Unhandled exceptions from C++ in `pygambit`

### ISSUE THREAD

**Issue by tturocy** [gambitproject/gambit#391]
## Overview

In the Cython wrapper definitions file `gambit.pxd`, not all functions are declared with `except +`.  This means that if any of these functions does raise an exception, the result is an unhandled C++ exception which in general terminates the Python interpreter.

We mostly guard against this at the Cython level, but at the moment this does lead to problems in the case of invalid mixed strategy and behavior profiles, as in #389.

## To do

The most straightforward solution is to wrap everything with `except +`, which at least will convert all exceptions to a generic Python `RuntimeError` exception.

Before doing so it might be worth taking a few minutes to understand whether there are any costs to doing this, as there are a number of functions which really ought never to throw an exception unless something is horribly wrong.

**Comment by rahulsavani** [comment]
Since it wasn't clear to me why some additions of "except +" would break compilation, I choose to try except absolutely everywhere -- the only cases now where we don't have it is where having it breaks compilation (in which case it is there but commented out, with the extra comment "doesn't compile"). 

The new tests are only for cases where I managed to trigger these exceptions, which are all variants of the example from 389, using payoff or liap value.

Let me know what you suggest to push, but I thought you'd want to see which ones were breaking compilation anyway.
